# Generated by Django 5.1.3 on 2024-11-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_page_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True, verbose_name='アクセス日時')),
                ('anniv1', models.CharField(max_length=50, verbose_name='記念日1')),
                ('anniv2', models.CharField(max_length=50, verbose_name='記念日2')),
                ('anniv3', models.CharField(max_length=50, verbose_name='記念日3')),
                ('anniv4', models.CharField(max_length=50, verbose_name='記念日4')),
                ('anniv5', models.CharField(max_length=50, verbose_name='記念日5')),
            ],
        ),
    ]
