# Generated by Django 5.1.3 on 2024-11-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_anniversary_anniv1_alter_anniversary_anniv2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
