# Generated by Django 5.1.3 on 2024-11-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_anniversary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
